services:
  printbot:
    build:
      context: .
      args:
        VERSION: "1.0.0"
    image: ghcr.io/zr0aces/printbot:1.0.0
    container_name: printbot
    restart: always
    environment:
      - CUPS_SERVER=cups
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
